### ISSUE TITLE
mixlib-shellout v2.1.0 breaks vagrant-docker

### ISSUE THREAD

**Issue by patcon** [test-kitchen/kitchen-docker#129]
Not sure exactly what happened, but vagrant-docker stopped working when mixlib-shellout, goes from v2.0.1 to v2.1.0:
https://github.com/chef/mixlib-shellout/blob/master/CHANGELOG.md#release-210

I could do more digging, but adding this would seem to be the most communicative and effective way of fixing this for now:

``` rb
gem "mixlib-shellout", "< 2.1.0"
```

This was the error that appeared:

```
~/repos/chef-confluence (master ✘)✹✭ ᐅ kitchen list
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::UserError
>>>>>> Message: You must first install the Docker CLI tool http://www.docker.io/gettingstarted/
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

I have docker installed and can use it fine and soon as I add that constraint :)

**Comment by patcon** [comment]
bump?

**Comment by sworisbreathing** [comment]
I just ran into this issue as well. Here's my kitchen.log:
```
I, [2015-12-22T11:14:06.450872 #5716]  INFO -- Kitchen: -----> Starting Kitchen (v1.4.2)
E, [2015-12-22T11:14:06.481242 #5716] ERROR -- Kitchen: ------Exception-------
E, [2015-12-22T11:14:06.481338 #5716] ERROR -- Kitchen: Class: Kitchen::UserError
E, [2015-12-22T11:14:06.481361 #5716] ERROR -- Kitchen: Message: You must first install the Docker CLI tool http://www.docker.io/gettingstarted/
E, [2015-12-22T11:14:06.481379 #5716] ERROR -- Kitchen: ---Nested Exception---
E, [2015-12-22T11:14:06.481394 #5716] ERROR -- Kitchen: Class: Kitchen::ShellOut::ShellCommandFailed
E, [2015-12-22T11:14:06.481408 #5716] ERROR -- Kitchen: Message: Expected process to exit with [0], but received '1'
---- Begin output of sudo -E docker >> /dev/null 2>&1 ----
STDOUT: 
STDERR: 
---- End output of sudo -E docker >> /dev/null 2>&1 ----
Ran sudo -E docker >> /dev/null 2>&1 returned 1
E, [2015-12-22T11:14:06.481423 #5716] ERROR -- Kitchen: ------Backtrace-------
E, [2015-12-22T11:14:06.481436 #5716] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/kitchen-docker-2.3.0/lib/kitchen/driver/docker.rb:76:in `rescue in verify_dependencies'
E, [2015-12-22T11:14:06.481450 #5716] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/kitchen-docker-2.3.0/lib/kitchen/driver/docker.rb:74:in `verify_dependencies'
E, [2015-12-22T11:14:06.481465 #5716] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/driver.rb:45:in `for_plugin'
E, [2015-12-22T11:14:06.481479 #5716] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/config.rb:226:in `new_driver'
E, [2015-12-22T11:14:06.481493 #5716] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/config.rb:239:in `new_instance'
E, [2015-12-22T11:14:06.481507 #5716] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/config.rb:135:in `block in build_instances'
E, [2015-12-22T11:14:06.481522 #5716] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/config.rb:134:in `map'
E, [2015-12-22T11:14:06.481561 #5716] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/config.rb:134:in `with_index'
E, [2015-12-22T11:14:06.481575 #5716] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/config.rb:134:in `build_instances'
E, [2015-12-22T11:14:06.481590 #5716] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/config.rb:110:in `instances'
E, [2015-12-22T11:14:06.481604 #5716] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/command.rb:115:in `filtered_instances'
E, [2015-12-22T11:14:06.481617 #5716] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/command.rb:145:in `parse_subcommand'
E, [2015-12-22T11:14:06.481631 #5716] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/command/test.rb:43:in `block in call'
E, [2015-12-22T11:14:06.481644 #5716] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
E, [2015-12-22T11:14:06.481658 #5716] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/command/test.rb:41:in `call'
E, [2015-12-22T11:14:06.481672 #5716] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/cli.rb:56:in `perform'
E, [2015-12-22T11:14:06.481716 #5716] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/cli.rb:217:in `test'
E, [2015-12-22T11:14:06.481730 #5716] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
E, [2015-12-22T11:14:06.481744 #5716] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
E, [2015-12-22T11:14:06.481758 #5716] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/cli.rb:308:in `invoke_task'
E, [2015-12-22T11:14:06.481787 #5716] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
E, [2015-12-22T11:14:06.481804 #5716] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
E, [2015-12-22T11:14:06.481818 #5716] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/bin/kitchen:13:in `block in <top (required)>'
E, [2015-12-22T11:14:06.481891 #5716] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/lib/kitchen/errors.rb:154:in `with_friendly_errors'
E, [2015-12-22T11:14:06.481907 #5716] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.2/bin/kitchen:13:in `<top (required)>'
E, [2015-12-22T11:14:06.481921 #5716] ERROR -- Kitchen: /opt/chefdk/bin/kitchen:14:in `load'
E, [2015-12-22T11:14:06.481934 #5716] ERROR -- Kitchen: /opt/chefdk/bin/kitchen:14:in `<main>'
```

I have docker installed, and verified that the command returns a zero status:
```bash
$ sudo -E docker >> /dev/null 2>&1
$ echo "$?"
0
```

I think the problem sits somewhere between test-kitchen and mixlib-shellout, so there's probably a case for raising a bug report against `Kitchen::Driver::SSHBase`. However, since that class is deprecated anyway, it might be a good idea for the docker driver to inherit from `Kitchen::Driver::Base` instead.

**Comment by sworisbreathing** [comment]
The issue appears to be sudo-related. if I disable sudo in my kitchen.yml, then kitchen-docker runs just fine.

```yaml
---
driver:
  name: docker
  use_sudo: false
...
```
(NB: my user is a member of the `docker` group, so I can run `docker` without sudo)

**Comment by jeffreycoe** [comment]
Closing issue due to inactivity. Please open a new issue if there is still a problem. Thanks!
