### ISSUE TITLE
Support for Oracle docker images

### ISSUE THREAD

**Issue by santoshgokak** [test-kitchen/kitchen-docker#131]
OracleLinux is already supported on Docker but not by kitchen-docker.
Any suggestions/plans to support this?

I get below trace

```
E, [2015-06-04T14:38:31.486728 #25300] ERROR -- default-oraclelinux: Class: Kitchen::ActionFailed
E, [2015-06-04T14:38:31.486819 #25300] ERROR -- default-oraclelinux: Message: Unknown platform 'oraclelinux'
E, [2015-06-04T14:38:31.486904 #25300] ERROR -- default-oraclelinux: ------Backtrace-------
E, [2015-06-04T14:38:31.486988 #25300] ERROR -- default-oraclelinux: /var/lib/gems/1.9.1/gems/kitchen-docker-2.1.0/lib/kitchen/driver/docker.rb:172:in `build_dockerfile'
E, [2015-06-04T14:38:31.487071 #25300] ERROR -- default-oraclelinux: /var/lib/gems/1.9.1/gems/kitchen-docker-2.1.0/lib/kitchen/driver/docker.rb:198:in `dockerfile'
E, [2015-06-04T14:38:31.487156 #25300] ERROR -- default-oraclelinux: /var/lib/gems/1.9.1/gems/kitchen-docker-2.1.0/lib/kitchen/driver/docker.rb:215:in `build_image'
E, [2015-06-04T14:38:31.487240 #25300] ERROR -- default-oraclelinux: /var/lib/gems/1.9.1/gems/kitchen-docker-2.1.0/lib/kitchen/driver/docker.rb:94:in `create'
E, [2015-06-04T14:38:31.487335 #25300] ERROR -- default-oraclelinux: /var/lib/gems/1.9.1/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:273:in `public_send'
E, [2015-06-04T14:38:31.487429 #25300] ERROR -- default-oraclelinux: /var/lib/gems/1.9.1/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:273:in `block in perform_action'
E, [2015-06-04T14:38:31.487512 #25300] ERROR -- default-oraclelinux: /var/lib/gems/1.9.1/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:308:in `call'
E, [2015-06-04T14:38:31.487590 #25300] ERROR -- default-oraclelinux: /var/lib/gems/1.9.1/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:308:in `synchronize_or_call'
E, [2015-06-04T14:38:31.487775 #25300] ERROR -- default-oraclelinux: /var/lib/gems/1.9.1/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:283:in `block in action'
E, [2015-06-04T14:38:31.487867 #25300] ERROR -- default-oraclelinux: /usr/lib/ruby/1.9.1/benchmark.rb:280:in `measure'
E, [2015-06-04T14:38:31.487952 #25300] ERROR -- default-oraclelinux: /var/lib/gems/1.9.1/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:282:in `action'
E, [2015-06-04T14:38:31.488032 #25300] ERROR -- default-oraclelinux: /var/lib/gems/1.9.1/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:273:in `perform_action'
E, [2015-06-04T14:38:31.488117 #25300] ERROR -- default-oraclelinux: /var/lib/gems/1.9.1/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:252:in `create_action'
E, [2015-06-04T14:38:31.488196 #25300] ERROR -- default-oraclelinux: /var/lib/gems/1.9.1/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:246:in `block in transition_to'
E, [2015-06-04T14:38:31.488286 #25300] ERROR -- default-oraclelinux: /var/lib/gems/1.9.1/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:245:in `each'
E, [2015-06-04T14:38:31.488369 #25300] ERROR -- default-oraclelinux: /var/lib/gems/1.9.1/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:245:in `transition_to'
E, [2015-06-04T14:38:31.488454 #25300] ERROR -- default-oraclelinux: /var/lib/gems/1.9.1/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:108:in `create'
E, [2015-06-04T14:38:31.488537 #25300] ERROR -- default-oraclelinux: /var/lib/gems/1.9.1/gems/test-kitchen-1.2.1/lib/kitchen/command.rb:109:in `public_send'
E, [2015-06-04T14:38:31.488623 #25300] ERROR -- default-oraclelinux: /var/lib/gems/1.9.1/gems/test-kitchen-1.2.1/lib/kitchen/command.rb:109:in `block (2 levels) in run_action'
E, [2015-06-04T14:38:31.488705 #25300] ERROR -- default-oraclelinux: ----------------------
```

**Comment by xmik** [comment]
For now you can use custom Dockerfile and later share how it could look like for OracleLinux.

**Comment by StuporHero** [comment]
Oracle Linux is a RHEL clone like CentOS. You should be able to use the same Dockerfile as with RHEL, CentOS, and Fedora.

**Comment by tas50** [comment]
This has been merged to master
