### ISSUE TITLE
Kitchen setup fails with error [Errno 13] Permission denied

### ISSUE THREAD

**Issue by srkolli** [test-kitchen/kitchen-docker#289]
## Kitchen setup command fails with the following error :

fatal: [localhost]: FAILED! => {"changed": false, "cmd": "rvm install 2.4.4", "msg": "[Errno 13] Permission denied", "rc": 13}

## Gem versions

rvm default do gem list | grep kitchen
 kitchen-ansible (0.48.1)
 kitchen-docker (2.6.0)
 test-kitchen (1.20.0)

rvm default do gem list | grep test
  minitest (5.10.3)
  test-kitchen (1.20.0)
  test-unit (3.2.7)

rvm default do gem list | grep ssh
 net-ssh (4.2.0)
 net-ssh-gateway (1.3.0)

## The contents of .kitchen.yml are 
---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  ansible_verbose: false
  ansible_verbosity: 2
  roles_path: "../../roles"
  gextra_vars_file: "vars/main.yml"

verifier:
  name: busser
  sudo: true
  sudo_command: sudo

platforms:
  - name: centos-7.2

suites:
  - name: default

## Error in  .kitchen/logs/default-centos-72.log  

E, [2018-03-30T21:12:42.064111 #12963] ERROR -- default-centos-72: /opt/rvm/gems/ruby-2.5.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:146:in `setup'
E, [2018-03-30T21:12:42.064121 #12963] ERROR -- default-centos-72: /opt/rvm/gems/ruby-2.5.0/gems/test-kitchen-1.20.0/lib/kitchen/command.rb:197:in `public_send'
E, [2018-03-30T21:12:42.064132 #12963] ERROR -- default-centos-72: /opt/rvm/gems/ruby-2.5.0/gems/test-kitchen-1.20.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2018-03-30T21:12:42.064141 #12963] ERROR -- default-centos-72: /opt/rvm/gems/ruby-2.5.0/gems/test-kitchen-1.20.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2018-03-30T21:12:42.064151 #12963] ERROR -- default-centos-72: ----End Backtrace-----
E, [2018-03-30T21:12:42.064170 #12963] ERROR -- default-centos-72: ---Nested Exception---
E, [2018-03-30T21:12:42.064181 #12963] ERROR -- default-centos-72: Class: Kitchen::Transport::SshFailed
E, [2018-03-30T21:12:42.064191 #12963] ERROR -- default-centos-72: Message: SSH exited (2) for command: [

          ANSIBLE_ROLES_PATH=/tmp/kitchen/roles sudo -E -s  ansible-playbook -i /tmp/kitchen/hosts  -c local -M /tmp/kitchen/modules          /tmp/kitchen/default.yml
]
E, [2018-03-30T21:12:42.064201 #12963] ERROR -- default-centos-72: ----------------------
E, [2018-03-30T21:12:42.064210 #12963] ERROR -- default-centos-72: ------Backtrace-------
E, [2018-03-30T21:12:42.064220 #12963] ERROR -- default-centos-72: /opt/rvm/gems/ruby-2.5.0/gems/test-kitchen-1.20.0/lib/kitchen/provisioner/base.rb:91:in `rescue in call'
E, [2018-03-30T21:12:42.064229 #12963] ERROR -- default-centos-72: /opt/rvm/gems/ruby-2.5.0/gems/test-kitchen-1.20.0/lib/kitchen/provisioner/base.rb:67:in `call'
E, [2018-03-30T21:12:42.064238 #12963] ERROR -- default-centos-72: /opt/rvm/gems/ruby-2.5.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:393:in `block in converge_action'
E, [2018-03-30T21:12:42.064248 #12963] ERROR -- default-centos-72: /opt/rvm/gems/ruby-2.5.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:536:in `synchronize_or_call'
E, [2018-03-30T21:12:42.064258 #12963] ERROR -- default-centos-72: /opt/rvm/gems/ruby-2.5.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:498:in `block in action'
E, [2018-03-30T21:12:42.064267 #12963] ERROR -- default-centos-72: /opt/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
E, [2018-03-30T21:12:42.064277 #12963] ERROR -- default-centos-72: /opt/rvm/gems/ruby-2.5.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:497:in `action'
E, [2018-03-30T21:12:42.064287 #12963] ERROR -- default-centos-72: /opt/rvm/gems/ruby-2.5.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:389:in `converge_action'
E, [2018-03-30T21:12:42.064296 #12963] ERROR -- default-centos-72: /opt/rvm/gems/ruby-2.5.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:368:in `block in transition_to'
E, [2018-03-30T21:12:42.064306 #12963] ERROR -- default-centos-72: /opt/rvm/gems/ruby-2.5.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:367:in `each'
E, [2018-03-30T21:12:42.064316 #12963] ERROR -- default-centos-72: /opt/rvm/gems/ruby-2.5.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:367:in `transition_to'
E, [2018-03-30T21:12:42.064326 #12963] ERROR -- default-centos-72: /opt/rvm/gems/ruby-2.5.0/gems/test-kitchen-1.20.0/lib/kitchen/instance.rb:146:in `setup'
E, [2018-03-30T21:12:42.064336 #12963] ERROR -- default-centos-72: /opt/rvm/gems/ruby-2.5.0/gems/test-kitchen-1.20.0/lib/kitchen/command.rb:197:in `public_send'
E, [2018-03-30T21:12:42.064345 #12963] ERROR -- default-centos-72: /opt/rvm/gems/ruby-2.5.0/gems/test-kitchen-1.20.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
tchen/logs/default-centos-72.logE, [2018-03-30T21:12:42.064355 #12963] ERROR -- default-centos-72: /opt/rvm/gems/ruby-2.5.0/gems/test-kitchen-1.20.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2018-03-30T21:12:42.064364 #12963] ERROR -- default-centos-72: ----End Backtrace-----
~

**Comment by srkolli** [comment]
I figured it out..
