### ISSUE TITLE
Does not work with BuildKit

### ISSUE THREAD

**Issue by CpuID** [test-kitchen/kitchen-docker#337]
```
I, [2019-05-15T04:14:03.216197 #58701]  INFO -- default-centos-69: #17 [13/13] COPY site-cookbooks/ted_ohai_plugins/files/default/ohai_plugins/...
I, [2019-05-15T04:14:03.216213 #58701]  INFO -- default-centos-69: #17 CACHED
I, [2019-05-15T04:14:03.216225 #58701]  INFO -- default-centos-69: 
I, [2019-05-15T04:14:03.216237 #58701]  INFO -- default-centos-69: #18 exporting to image
I, [2019-05-15T04:14:03.216249 #58701]  INFO -- default-centos-69: #18 exporting layers done
I, [2019-05-15T04:14:03.216262 #58701]  INFO -- default-centos-69: #18 writing image sha256:10ef8aa4cf4c1cd7b43285ba94b48a975662e64e9e559c8244c486a824f78400 done
I, [2019-05-15T04:14:03.216276 #58701]  INFO -- default-centos-69: #18 DONE 0.0s
E, [2019-05-15T04:14:03.231990 #58701] ERROR -- default-centos-69: Create failed on instance <default-centos-69>.
E, [2019-05-15T04:14:03.232106 #58701] ERROR -- default-centos-69: ------Exception-------
E, [2019-05-15T04:14:03.232128 #58701] ERROR -- default-centos-69: Class: Kitchen::ActionFailed
E, [2019-05-15T04:14:03.232141 #58701] ERROR -- default-centos-69: Message: Could not parse Docker build output for image ID
E, [2019-05-15T04:14:03.232152 #58701] ERROR -- default-centos-69: ----------------------
E, [2019-05-15T04:14:03.232162 #58701] ERROR -- default-centos-69: ------Backtrace-------
E, [2019-05-15T04:14:03.232171 #58701] ERROR -- default-centos-69: /home/nathan/.rvm/gems/ruby-2.5.0@chef-repo/gems/kitchen-docker-2.9.0/lib/kitchen/driver/docker.rb:315:in `parse_image_id'
E, [2019-05-15T04:14:03.232182 #58701] ERROR -- default-centos-69: /home/nathan/.rvm/gems/ruby-2.5.0@chef-repo/gems/kitchen-docker-2.9.0/lib/kitchen/driver/docker.rb:335:in `build_image'
E, [2019-05-15T04:14:03.232192 #58701] ERROR -- default-centos-69: /home/nathan/.rvm/gems/ruby-2.5.0@chef-repo/gems/kitchen-docker-2.9.0/lib/kitchen/driver/docker.rb:122:in `create'
E, [2019-05-15T04:14:03.232202 #58701] ERROR -- default-centos-69: /home/nathan/.rvm/gems/ruby-2.5.0@chef-repo/gems/test-kitchen-2.2.4/lib/kitchen/instance.rb:484:in `public_send'
E, [2019-05-15T04:14:03.232212 #58701] ERROR -- default-centos-69: /home/nathan/.rvm/gems/ruby-2.5.0@chef-repo/gems/test-kitchen-2.2.4/lib/kitchen/instance.rb:484:in `block in perform_action'
E, [2019-05-15T04:14:03.232222 #58701] ERROR -- default-centos-69: /home/nathan/.rvm/gems/ruby-2.5.0@chef-repo/gems/test-kitchen-2.2.4/lib/kitchen/instance.rb:551:in `synchronize_or_call'
E, [2019-05-15T04:14:03.232236 #58701] ERROR -- default-centos-69: /home/nathan/.rvm/gems/ruby-2.5.0@chef-repo/gems/test-kitchen-2.2.4/lib/kitchen/instance.rb:513:in `block in action'
E, [2019-05-15T04:14:03.232266 #58701] ERROR -- default-centos-69: /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
E, [2019-05-15T04:14:03.232278 #58701] ERROR -- default-centos-69: /home/nathan/.rvm/gems/ruby-2.5.0@chef-repo/gems/test-kitchen-2.2.4/lib/kitchen/instance.rb:512:in `action'
E, [2019-05-15T04:14:03.232288 #58701] ERROR -- default-centos-69: /home/nathan/.rvm/gems/ruby-2.5.0@chef-repo/gems/test-kitchen-2.2.4/lib/kitchen/instance.rb:484:in `perform_action'
E, [2019-05-15T04:14:03.232298 #58701] ERROR -- default-centos-69: /home/nathan/.rvm/gems/ruby-2.5.0@chef-repo/gems/test-kitchen-2.2.4/lib/kitchen/instance.rb:394:in `create_action'
E, [2019-05-15T04:14:03.232307 #58701] ERROR -- default-centos-69: /home/nathan/.rvm/gems/ruby-2.5.0@chef-repo/gems/test-kitchen-2.2.4/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
E, [2019-05-15T04:14:03.232317 #58701] ERROR -- default-centos-69: /home/nathan/.rvm/gems/ruby-2.5.0@chef-repo/gems/test-kitchen-2.2.4/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
E, [2019-05-15T04:14:03.232334 #58701] ERROR -- default-centos-69: /home/nathan/.rvm/gems/ruby-2.5.0@chef-repo/gems/test-kitchen-2.2.4/lib/kitchen/instance.rb:381:in `block in transition_to'
E, [2019-05-15T04:14:03.232347 #58701] ERROR -- default-centos-69: /home/nathan/.rvm/gems/ruby-2.5.0@chef-repo/gems/test-kitchen-2.2.4/lib/kitchen/instance.rb:380:in `each'
E, [2019-05-15T04:14:03.232357 #58701] ERROR -- default-centos-69: /home/nathan/.rvm/gems/ruby-2.5.0@chef-repo/gems/test-kitchen-2.2.4/lib/kitchen/instance.rb:380:in `transition_to'
E, [2019-05-15T04:14:03.232368 #58701] ERROR -- default-centos-69: /home/nathan/.rvm/gems/ruby-2.5.0@chef-repo/gems/test-kitchen-2.2.4/lib/kitchen/instance.rb:140:in `converge'
E, [2019-05-15T04:14:03.232378 #58701] ERROR -- default-centos-69: /home/nathan/.rvm/gems/ruby-2.5.0@chef-repo/gems/test-kitchen-2.2.4/lib/kitchen/command.rb:197:in `public_send'
E, [2019-05-15T04:14:03.232388 #58701] ERROR -- default-centos-69: /home/nathan/.rvm/gems/ruby-2.5.0@chef-repo/gems/test-kitchen-2.2.4/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2019-05-15T04:14:03.232398 #58701] ERROR -- default-centos-69: /home/nathan/.rvm/gems/ruby-2.5.0@chef-repo/gems/test-kitchen-2.2.4/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2019-05-15T04:14:03.232407 #58701] ERROR -- default-centos-69: ----End Backtrace-----
```

Pretty sure this is simply going to be tweaking https://github.com/test-kitchen/kitchen-docker/blob/master/lib/kitchen/driver/docker.rb#L311-L312 to support the newer syntax. A la:

```
[nathan@ns-desktop-ub test-docker]$ env | grep BUILDKIT
DOCKER_BUILDKIT=1
 [nathan@ns-desktop-ub test-docker]$ docker build .
[+] Building 1.2s (6/6) FINISHED                                                                                                                                          
 => [internal] load .dockerignore                                                                                                                                    0.1s
 => => transferring context: 2B                                                                                                                                      0.1s
 => [internal] load build definition from Dockerfile                                                                                                                 0.1s
 => => transferring dockerfile: 84B                                                                                                                                  0.1s
 => [internal] load metadata for docker.io/library/alpine:3.9                                                                                                        0.0s
 => [1/2] FROM docker.io/library/alpine:3.9                                                                                                                          0.0s
 => => resolve docker.io/library/alpine:3.9                                                                                                                          0.0s
 => [2/2] RUN cat /etc/os-release                                                                                                                                    0.9s
 => exporting to image                                                                                                                                               0.1s
 => => exporting layers                                                                                                                                              0.1s
 => => writing image sha256:f1cb713897eaac22ff5010c721354b5eef8d58c590521ae93ceba00162cf19de                                                                         0.0s
```

**Comment by jeffj254** [comment]
Is there any progress on this?  Having to constantly disable and enable buildkit whenever I use test kitchen vs build docker images is quite a pain.

Our automation also can't handle both test kitchen and docker builds with secrets since each requires a different buildkit setting right now.

**Comment by CpuID** [comment]
@jeffj254 no news to my knowledge :(

**Comment by longspell** [comment]
> Is there any progress on this? Having to constantly disable and enable buildkit whenever I use test kitchen vs build docker images is quite a pain.

In the interim, you can prefix your `kitchen` command with `DOCKER_BUILDKIT=0` and it will override the environment variable or the docker daemon.json configuration value.  ie `DOCKER_BUILDKIT=0 kitchen create`

**Comment by vijjukumar** [comment]
Hi Team,

Still i am getting the error "Could not parse Docker build output for image ID"

Docker version 20.10.5, build 55c4c88
kitchen-docker-2.10.0

Added docker daemon config properties 
{
  "experimental": false,
  "debug": true,
  "features": {
    "buildkit": true
  }
}



cat .kitchen/logs/default-centos.log 
I, [2021-04-16T17:59:18.856423 #56567]  INFO -- default-centos: -----> Creating <default-centos>...
E, [2021-04-16T17:59:19.823754 #56567] ERROR -- default-centos: Create failed on instance <default-centos>.
E, [2021-04-16T17:59:19.823970 #56567] ERROR -- default-centos: ------Exception-------
E, [2021-04-16T17:59:19.824002 #56567] ERROR -- default-centos: Class: Kitchen::ActionFailed
E, [2021-04-16T17:59:19.824031 #56567] ERROR -- default-centos: Message: Could not parse Docker build output for image ID
E, [2021-04-16T17:59:19.824057 #56567] ERROR -- default-centos: ----------------------
E, [2021-04-16T17:59:19.824082 #56567] ERROR -- default-centos: ------Backtrace-------
