### ISSUE TITLE
docker build output no longer matches image_helper regex

### ISSUE THREAD

**Issue by longspell** [test-kitchen/kitchen-docker#378]
## :ghost: Brief Description

Unable to `kitchen create` any instances with kitchen-docker.

## Version

test kitchen 2.8.0
kitchen-docker 2.10.0
Docker version 20.10.0, build 7287ab3

## Environment

OSX (10.15.7)

## Scenario

`kitchen create` fails to create an instance when using the docker driver

## Steps to Reproduce

Generate a test cookbook with `chef generate cookbook test`, update `kitchen.yml` to use the docker driver and run `kitchen create`

Example:
```
---
driver:
  name: docker

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-20.04
  - name: centos-8

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
```

## Expected Result

kitchen instance is created

## Actual Result

Log reports `Could not parse Docker build output for image ID`

```
I, [2020-12-23T15:37:51.208931 #82950]  INFO -- default-ubuntu-2004: -----> Creating <default-ubuntu-2004>...
E, [2020-12-23T15:38:24.528327 #82950] ERROR -- default-ubuntu-2004: Create failed on instance <default-ubuntu-2004>.
E, [2020-12-23T15:38:24.528472 #82950] ERROR -- default-ubuntu-2004: ------Exception-------
E, [2020-12-23T15:38:24.528492 #82950] ERROR -- default-ubuntu-2004: Class: Kitchen::ActionFailed
E, [2020-12-23T15:38:24.528505 #82950] ERROR -- default-ubuntu-2004: Message: Could not parse Docker build output for image ID
E, [2020-12-23T15:38:24.528519 #82950] ERROR -- default-ubuntu-2004: ----------------------
E, [2020-12-23T15:38:24.528529 #82950] ERROR -- default-ubuntu-2004: ------Backtrace-------
E, [2020-12-23T15:38:24.528539 #82950] ERROR -- default-ubuntu-2004: /Users/longspell/.chefdk/gem/ruby/2.7.0/gems/kitchen-docker-2.10.0/lib/kitchen/docker/helpers/image_helper.rb:33:in `parse_image_id'
E, [2020-12-23T15:38:24.528549 #82950] ERROR -- default-ubuntu-2004: /Users/longspell/.chefdk/gem/ruby/2.7.0/gems/kitchen-docker-2.10.0/lib/kitchen/docker/helpers/image_helper.rb:59:in `build_image'
E, [2020-12-23T15:38:24.528560 #82950] ERROR -- default-ubuntu-2004: /Users/longspell/.chefdk/gem/ruby/2.7.0/gems/kitchen-docker-2.10.0/lib/kitchen/docker/container/linux.rb:38:in `create'
E, [2020-12-23T15:38:24.528570 #82950] ERROR -- default-ubuntu-2004: /Users/longspell/.chefdk/gem/ruby/2.7.0/gems/kitchen-docker-2.10.0/lib/kitchen/driver/docker.rb:123:in `create'
E, [2020-12-23T15:38:24.528580 #82950] ERROR -- default-ubuntu-2004: /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:495:in `public_send'
E, [2020-12-23T15:38:24.528590 #82950] ERROR -- default-ubuntu-2004: /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:495:in `block in perform_action'
E, [2020-12-23T15:38:24.528600 #82950] ERROR -- default-ubuntu-2004: /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:563:in `synchronize_or_call'
E, [2020-12-23T15:38:24.528610 #82950] ERROR -- default-ubuntu-2004: /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:524:in `block in action'
E, [2020-12-23T15:38:24.528620 #82950] ERROR -- default-ubuntu-2004: /Users/longspell/.chefdk/gem/ruby/2.7.0/gems/benchmark-0.1.0/lib/benchmark.rb:293:in `measure'
E, [2020-12-23T15:38:24.528633 #82950] ERROR -- default-ubuntu-2004: /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:523:in `action'
E, [2020-12-23T15:38:24.528644 #82950] ERROR -- default-ubuntu-2004: /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:495:in `perform_action'
E, [2020-12-23T15:38:24.528654 #82950] ERROR -- default-ubuntu-2004: /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:404:in `create_action'
E, [2020-12-23T15:38:24.528664 #82950] ERROR -- default-ubuntu-2004: /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:392:in `block (2 levels) in transition_to'
E, [2020-12-23T15:38:24.528674 #82950] ERROR -- default-ubuntu-2004: /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/lifecycle_hooks.rb:44:in `run_with_hooks'
E, [2020-12-23T15:38:24.528684 #82950] ERROR -- default-ubuntu-2004: /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:391:in `block in transition_to'
E, [2020-12-23T15:38:24.528695 #82950] ERROR -- default-ubuntu-2004: /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:390:in `each'
E, [2020-12-23T15:38:24.528705 #82950] ERROR -- default-ubuntu-2004: /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:390:in `transition_to'
E, [2020-12-23T15:38:24.528715 #82950] ERROR -- default-ubuntu-2004: /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:128:in `create'
E, [2020-12-23T15:38:24.528793 #82950] ERROR -- default-ubuntu-2004: /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/command.rb:195:in `public_send'
E, [2020-12-23T15:38:24.528805 #82950] ERROR -- default-ubuntu-2004: /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/command.rb:195:in `run_action_in_thread'
E, [2020-12-23T15:38:24.528814 #82950] ERROR -- default-ubuntu-2004: /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.8.0/lib/kitchen/command.rb:166:in `block (2 levels) in run_action'
E, [2020-12-23T15:38:24.528822 #82950] ERROR -- default-ubuntu-2004: /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
E, [2020-12-23T15:38:24.528830 #82950] ERROR -- default-ubuntu-2004: ----End Backtrace-----
```

## :heavy_plus_sign: Additional context

If I manually run `docker build` I can see none of the output matches `image_helper.rb`'s `if line =~ /image id|build successful|successfully built/i`

**Comment by longspell** [comment]
Discovered default settings enable buildkit which causes the issue.  Duplicate of https://github.com/test-kitchen/kitchen-docker/issues/225.
